services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: video_courses_mvp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: